name: .NET CI Pipeline

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET 9
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Restore dependencies
      run: dotnet restore src/WorkOrderManagement/WorkOrderManagement.csproj && dotnet restore src/WorkOrderManagement.Tests/WorkOrderManagement.Tests.csproj

    - name: Build
      run: dotnet build src/WorkOrderManagement/WorkOrderManagement.csproj --no-restore && dotnet build src/WorkOrderManagement.Tests/WorkOrderManagement.Tests.csproj --no-restore

    - name: Test
      run: dotnet test src/WorkOrderManagement.Tests/WorkOrderManagement.Tests.csproj --no-build --verbosity normal
